name: CI/CD for Multiple Services - Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-push:
    environment: staging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth
          - data
          - chat
          - core

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}-dp:v1.0

  deploy:
    environment: staging
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo docker-compose -f /var/www/dp/docker-compose.yml down || true
            
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/auth-dp:v1.0
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/data-dp:v1.0
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/chat-dp:v1.0
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/core-dp:v1.0

            sudo docker-compose -f /var/www/dp/docker-compose.yml up -d